-- AlterTable
ALTER TABLE "Asset" ADD COLUMN     "description" TEXT,
ADD COLUMN     "height" DOUBLE PRECISION DEFAULT 150,
ADD COLUMN     "positionX" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "positionY" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "rotation" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "showDescription" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "width" DOUBLE PRECISION DEFAULT 200,
ADD COLUMN     "zIndex" INTEGER DEFAULT 1;
